language: node_js

node_js:
  - "8.2.1"

script:
  - npm test

services:
  - postgresql

before_script:
  - psql -c 'create database more-recipes-db;' -U postgres

after_success:
   - npm run coverage